const defaultTopologyConfig = {
  version: 1,
  nodes: [
    { id: "client-us", label: "Client", kind: "client", x: 90, y: 220, r: 38, lat: 39.5, lon: -98.3 },
    { id: "flareless", label: "Flareless", kind: "director", x: 310, y: 220, r: 52, lat: 32.0, lon: -35.0 },
    { id: "cdn-a", label: "Cloudflare", kind: "provider", x: 550, y: 92, r: 42, lat: 50.1, lon: -5.1 },
    { id: "cdn-b", label: "Fastly", kind: "provider", x: 550, y: 220, r: 42, lat: 1.3, lon: 103.8 },
    { id: "cdn-c", label: "CloudFront", kind: "provider", x: 550, y: 348, r: 42, lat: 35.7, lon: 139.7 },
    { id: "peer-assisted-edge", label: "Micro CDN", kind: "peer", x: 790, y: 112, r: 44, lat: -23.5, lon: 133.8 },
    { id: "origin", label: "Origin", kind: "origin", x: 790, y: 220, r: 44, lat: 52.5, lon: 13.4 }
  ],
  links: [
    { id: "ingress", from: "client-us", to: "flareless", label: "ingress" },
    { id: "cloudflare", from: "flareless", to: "cdn-a", label: "24 ms" },
    { id: "fastly", from: "flareless", to: "cdn-b", label: "18 ms" },
    { id: "cloudfront", from: "flareless", to: "cdn-c", label: "31 ms" },
    { id: "micro-cdn", from: "flareless", to: "peer-assisted-edge", label: "hash verified" },
    { id: "origin", from: "cdn-b", to: "origin", label: "origin" }
  ]
};

const state = {
  baseUrl: window.FLARELESS_BASE_URL || "http://127.0.0.1:8765",
  timer: null,
  map: null,
  mapReady: false,
  currentPage: "dashboard",
  scenarioId: "healthy-route",
  activeProvider: null,
  routeTrace: {},
  providers: [],
  recommendations: [],
  auditLog: [],
  headers: {},
  micro: {},
  policyFormat: "yaml",
  conditions: ["HTTP status is 5xx", "Provider is primary CDN"],
  providerMarkers: {},
  animationTick: 0,
  history: [],
  events: [],
  metrics: { requests: [62, 66, 74, 70, 82, 91, 88, 97], latency: [18, 22, 16, 28, 31, 20, 15, 19], errors: [1, 1, 2, 3, 8, 4, 2, 1] },
  replayIndex: 0,
  scenarioFormat: "json",
  scenarioSteps: [{ provider: "cdn-c", result: "TIMEOUT" }, { provider: "cdn-b", result: "BLOCKED" }, { provider: "cdn-a", result: "PROVIDER_SUCCESS" }],
  topologyConfig: structuredClone(defaultTopologyConfig),
};

let nodes = {};
const resultOptions = ["PROVIDER_SUCCESS", "TIMEOUT", "BLOCKED", "HTTP_5XX", "ORIGIN_BLOCKED", "NO_HEALTHY_NODE", "ADVERTISES_CONTENT"];

function $(id) { return document.getElementById(id); }
function nowTime() { return new Date().toLocaleTimeString(); }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }
function recordEvent(type, payload = {}) { state.events.unshift({ time: nowTime(), type, payload }); state.events = state.events.slice(0, 120); }
function toast(message) { const box = $("toast"); if (!box) return; box.textContent = message; box.classList.add("show"); setTimeout(() => box.classList.remove("show"), 2200); }
async function api(path, body) { const options = body ? { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : { cache: "no-store" }; const response = await fetch(state.baseUrl + path, options); if (!response.ok) throw new Error(`${path} ${response.status}`); return response.json(); }

function injectOperationalStyles() {
  const style = document.createElement("style");
  style.textContent = `.details-drawer{position:fixed;right:0;top:0;bottom:0;width:380px;max-width:92vw;background:rgba(7,16,27,.96);border-left:1px solid rgba(119,238,202,.42);box-shadow:-18px 0 40px rgba(0,0,0,.44);z-index:60;transform:translateX(104%);transition:.18s ease;padding:18px;color:#ecf5ff;overflow:auto}.details-drawer.open{transform:translateX(0)}.drawer-close{position:absolute;right:12px;top:10px;border-radius:999px;padding:3px 10px;font-size:20px}.drawer-title{font-weight:800;font-size:18px;margin:24px 0 4px}.drawer-sub{font:12px Consolas,monospace;color:#91a4b5;margin-bottom:14px}.kv{display:grid;grid-template-columns:120px 1fr;gap:8px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.08);font-size:12px}.kv span:first-child{color:#91a4b5}.scenario-step{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:8px 0}.scenario-step select{width:100%}.topology-edge-label{fill:#91a4b5;font:11px Consolas}.topology-edge-label.active{fill:#46f0a0}.topology-edge-label.failed{fill:#f04455}.clickable-topology{cursor:pointer}.clickable-topology:hover circle{stroke-width:5}.active-path{filter:url(#greenGlow)}.topology-live-grid{display:grid;grid-template-columns:minmax(0,1.75fr) minmax(300px,.8fr);gap:14px;height:100%;min-height:0}.topology-editor{display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;gap:10px;min-height:0;background:#07111b;border:1px solid rgba(255,255,255,.07);border-radius:12px;padding:12px}.topology-editor span{font-size:11px;color:#91a4b5}.topology-editor textarea{width:100%;height:100%;resize:none;background:#050c14;color:#d8e9ff;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:10px;font:11px Consolas,monospace}.topology-edge-metric{fill:#bcd1df;font:10px Consolas}.topology-node-shadow{opacity:.16}@media(max-width:1300px){.topology-live-grid{grid-template-columns:1fr}.topology-editor{display:none}}`;
  document.head.appendChild(style);
}

function syncNodeRegistry() { nodes = {}; for (const n of topologyNodes()) nodes[n.id] = { label: n.label, lat: n.lat ?? 0, lon: n.lon ?? 0, kind: n.kind || "provider" }; }
function topologyNodes() { const configNodes = Array.isArray(state.topologyConfig.nodes) ? state.topologyConfig.nodes : []; const map = new Map(configNodes.map((n) => [n.id, { ...n }])); const providerIds = new Set([...(state.providers || []).map((p) => p.name), ...(state.routeTrace.attempts || []).map((a) => a.provider).filter(Boolean)]); let index = 0; for (const id of providerIds) if (!map.has(id)) map.set(id, { id, label: id, kind: "provider", x: 550, y: 96 + index++ * 72, r: 38 }); return [...map.values()]; }
function topologyLinks() { const configLinks = Array.isArray(state.topologyConfig.links) ? state.topologyConfig.links : []; const links = [...configLinks]; const linkedTo = new Set(links.map((l) => l.to)); for (const n of topologyNodes()) if (n.kind === "provider" && !linkedTo.has(n.id)) links.push({ id: `auto-${n.id}`, from: "flareless", to: n.id, label: "auto" }); return links; }
function providerIds() { return topologyNodes().filter((n) => ["provider", "peer"].includes(n.kind)).map((n) => n.id); }

function isGood(result) { return (result || "").includes("SUCCESS") || (result || "").includes("ADVERTISES_CONTENT"); }
function isFailed(result) { return (result || "").match(/TIMEOUT|BLOCKED|ERROR|OFFLINE|DISABLED|NO_HEALTHY|HTTP_/); }
function routeArc(from, to) { const output = []; const dx = (to.lon || 0) - (from.lon || 0); const lift = Math.min(32, Math.max(8, Math.abs(dx) * 0.12)); for (let step = 0; step <= 48; step += 1) { const t = step / 48; output.push([(from.lon || 0) + dx * t, (from.lat || 0) + ((to.lat || 0) - (from.lat || 0)) * t + Math.sin(Math.PI * t) * lift]); } return output; }
function nodeColor(id, result, activeProvider) { if (id === activeProvider) return "#46f0a0"; if (isFailed(result)) return "#f04455"; if (nodes[id]?.kind === "director") return "#f6b44c"; if (nodes[id]?.kind === "peer") return "#62c8ff"; return "#dbe7ff"; }
function replayTrace(trace = state.routeTrace, index = null) { if (index === null) return trace; const attempts = trace.attempts || []; const partialAttempts = attempts.slice(0, Math.max(0, index)); const finalAttempt = partialAttempts[partialAttempts.length - 1]; return { ...trace, attempts: partialAttempts, finalStatus: finalAttempt ? { provider: finalAttempt.provider, reason: finalAttempt.result, outcome: isGood(finalAttempt.result) ? "success" : "in-progress" } : { provider: "flareless", reason: "WAITING", outcome: "in-progress" } }; }
function routeSegments(trace) { const attempts = trace.attempts || []; const activeProvider = (trace.finalStatus || {}).provider || ""; const segments = [{ from: "client-us", to: "flareless", result: "PROVIDER_SUCCESS" }]; let last = "flareless"; for (const attempt of attempts) { if (!nodes[attempt.provider]) continue; segments.push({ from: last, to: attempt.provider, result: attempt.result || "UNKNOWN" }); last = attempt.provider; } if (activeProvider && nodes[activeProvider]) segments.push({ from: activeProvider, to: "client-us", result: "PROVIDER_SUCCESS" }); return segments; }
function buildMapGeoJson(trace, providers) { syncNodeRegistry(); const attempts = trace.attempts || []; const activeProvider = (trace.finalStatus || {}).provider || ""; const resultByProvider = Object.fromEntries(attempts.map((attempt) => [attempt.provider, attempt.result])); const features = []; for (const segment of routeSegments(trace)) { const from = nodes[segment.from]; const to = nodes[segment.to]; if (!from || !to) continue; features.push({ type: "Feature", geometry: { type: "LineString", coordinates: routeArc(from, to) }, properties: { kind: "route", good: isGood(segment.result), label: `${from.label} to ${to.label}: ${segment.result}` } }); } const visibleNodes = new Set(["client-us", "flareless", "origin", ...providers.map((p) => p.name), ...attempts.map((a) => a.provider).filter(Boolean)]); if (trace.selectedFallback === "peer-fallback") visibleNodes.add("peer-assisted-edge"); visibleNodes.forEach((id) => { const node = nodes[id]; if (!node) return; features.push({ type: "Feature", geometry: { type: "Point", coordinates: [node.lon || 0, node.lat || 0] }, properties: { kind: "node", id, label: node.label, result: resultByProvider[id] || node.kind, color: nodeColor(id, resultByProvider[id], activeProvider) } }); }); return { type: "FeatureCollection", features }; }

function initMap() { syncNodeRegistry(); state.map = new maplibregl.Map({ container: "map", style: "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json", center: [18, 18], zoom: 1.35, attributionControl: false, interactive: true }); state.map.addControl(new maplibregl.NavigationControl({ visualizePitch: true }), "top-right"); state.map.on("load", addMapLayers); }
function addMapLayers() { state.mapReady = true; state.map.addSource("flareless-live", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); state.map.addLayer({ id: "route-shadow", type: "line", source: "flareless-live", filter: ["==", ["get", "kind"], "route"], paint: { "line-color": "#053a2f", "line-width": 8, "line-opacity": 0.72 } }); state.map.addLayer({ id: "routes", type: "line", source: "flareless-live", filter: ["==", ["get", "kind"], "route"], paint: { "line-color": ["case", ["==", ["get", "good"], true], "#46f0a0", "#f04455"], "line-width": 3, "line-opacity": 0.9 } }); state.map.addLayer({ id: "routes-flow", type: "line", source: "flareless-live", filter: ["==", ["get", "kind"], "route"], paint: { "line-color": ["case", ["==", ["get", "good"], true], "#b5ffd8", "#ff8793"], "line-width": 2, "line-opacity": 0.9, "line-dasharray": [0.1, 2.2] } }); state.map.addLayer({ id: "node-glow", type: "circle", source: "flareless-live", filter: ["==", ["get", "kind"], "node"], paint: { "circle-radius": ["case", ["==", ["get", "id"], "flareless"], 22, 15], "circle-color": ["get", "color"], "circle-opacity": 0.16, "circle-blur": 0.65 } }); state.map.addLayer({ id: "nodes", type: "circle", source: "flareless-live", filter: ["==", ["get", "kind"], "node"], paint: { "circle-radius": ["case", ["==", ["get", "id"], "flareless"], 10, 7], "circle-color": ["get", "color"], "circle-stroke-color": "#e8f5ff", "circle-stroke-width": 1.2 } }); state.map.addLayer({ id: "labels", type: "symbol", source: "flareless-live", filter: ["==", ["get", "kind"], "node"], layout: { "text-field": ["get", "label"], "text-size": 11, "text-offset": [1.1, -0.7], "text-anchor": "left" }, paint: { "text-color": "#eaf6ff", "text-halo-color": "#07101f", "text-halo-width": 1.2 } }); state.map.on("click", "nodes", (event) => { const feature = event.features?.[0]; if (!feature) return; openDetailsDrawer(feature.properties.id); }); animateRouteArcs(); }
function animateRouteArcs() { setInterval(() => { if (!state.mapReady || !state.map.getLayer("routes-flow")) return; state.animationTick = (state.animationTick + 1) % 18; state.map.setPaintProperty("routes-flow", "line-dasharray", [0.1 + state.animationTick * 0.08, 2.2, 0.1, 1.6]); }, 140); }

function providerDisplayName(provider) { return nodes[provider.name]?.label || provider.name; }
function providerStatusClass(provider) { if ((provider.lastResult || "").match(/TIMEOUT|BLOCKED|HTTP_|ERROR|OFFLINE/)) return "failed"; if (provider.status && provider.status !== "healthy") return "degraded"; return "healthy"; }
function providerBadge(provider) { const cls = providerStatusClass(provider); if (cls === "failed") return '<span class="badge fail">failed</span>'; if (cls === "degraded") return '<span class="badge warn">degraded</span>'; return '<span class="badge">healthy</span>'; }
function updateProviderMarkers(providers) { if (!state.mapReady) return; syncNodeRegistry(); for (const provider of providers) { const node = nodes[provider.name]; if (!node) continue; const statusClass = providerStatusClass(provider); const content = `<b>${providerDisplayName(provider)}</b><div class="marker-row"><span class="marker-dot"></span>${provider.latencyMs || "--"} ms · ${provider.lastResult || "standby"}</div>`; if (!state.providerMarkers[provider.name]) { const element = document.createElement("div"); element.className = `provider-marker ${statusClass}`; element.innerHTML = content; element.addEventListener("click", () => openDetailsDrawer(provider.name)); state.providerMarkers[provider.name] = new maplibregl.Marker({ element, anchor: "left", offset: [12, -12] }).setLngLat([node.lon || 0, node.lat || 0]).addTo(state.map); } else { const markerElement = state.providerMarkers[provider.name].getElement(); markerElement.className = `provider-marker ${statusClass}`; markerElement.innerHTML = content; markerElement.onclick = () => openDetailsDrawer(provider.name); state.providerMarkers[provider.name].setLngLat([node.lon || 0, node.lat || 0]); } state.providerMarkers[provider.name].getElement().style.borderColor = provider.name === state.activeProvider ? "rgba(70,240,160,.85)" : "rgba(255,255,255,.14)"; } }

async function refresh() { const [status, tracePayload, providerPayload, recommendations, audit, micro] = await Promise.all([api("/status"), api("/route/trace"), api("/providers"), api("/agent/recommendations"), api("/agent/audit-log"), api("/micro-cdn/status")]); state.scenarioId = status.scenarioId; state.activeProvider = status.activeProvider; state.routeTrace = tracePayload.routeTrace || {}; state.providers = providerPayload.providers || []; state.recommendations = recommendations.recommendations || []; state.auditLog = audit.auditLog || []; state.headers = tracePayload.headers || {}; state.micro = micro || {}; if (state.mapReady) { state.map.getSource("flareless-live")?.setData(buildMapGeoJson(state.routeTrace, state.providers)); updateProviderMarkers(state.providers); } renderAll(status); recordEvent("ROUTE_TRACE_UPDATED", { scenarioId: status.scenarioId, activeProvider: status.activeProvider }); }
function renderAll(status) { updateHeader(status); $("routeReason").textContent = status.routeReason || "None"; $("activeProviderPill").textContent = `active: ${status.activeProvider || "none"}`; $("trafficText").textContent = formatTraffic(status, state.routeTrace, state.providers); $("traceText").textContent = JSON.stringify(state.routeTrace, null, 2); $("traceEvidenceText").textContent = JSON.stringify(state.routeTrace, null, 2); $("headersText").textContent = formatHeaders(state.headers); $("auditText").textContent = JSON.stringify(state.auditLog, null, 2); $("diffText").textContent = formatDiff(status, state.routeTrace); renderProviders(); renderApprovals(); renderPeers(); renderPolicyCode(); renderReplay(); renderIncidents(); renderMetrics(); renderEvents(); renderTopology(); renderHistory(); renderExplanation(status); renderScenarioBuilder(); renderTopologyEditor(); }
function updateHeader(status) { const globalStatus = $("globalStatus"); const reason = status.routeReason || ""; globalStatus.classList.remove("degraded", "failed"); if (!reason || reason === "UNKNOWN") globalStatus.textContent = "STATUS: PAUSED"; else if (reason.includes("SUCCESS") || reason.includes("ADVERTISES_CONTENT")) globalStatus.textContent = "STATUS: OPTIMAL"; else if (reason.includes("FAILED") || reason.includes("BLOCKED") || reason.includes("NO_HEALTHY")) { globalStatus.textContent = "STATUS: FAILED"; globalStatus.classList.add("failed"); } else { globalStatus.textContent = "STATUS: DEGRADED"; globalStatus.classList.add("degraded"); } const liveState = $("liveState"); liveState.textContent = state.timer ? "live" : "paused"; liveState.className = state.timer ? "live-state" : "live-state paused"; }
function renderProviders() { $("providersTable").innerHTML = state.providers.map((p) => `<tr onclick="openDetailsDrawer('${p.name}')"><td>${providerDisplayName(p)}</td><td>${providerBadge(p)}</td><td>${p.latencyMs || "--"} ms</td><td>${p.lastResult || "--"}</td><td>${p.name === state.activeProvider ? "active" : "standby"}</td></tr>`).join(""); }
function renderApprovals() { const container = $("approvalCards"); if (!state.recommendations.length) container.textContent = "No recommendations loaded."; else container.innerHTML = state.recommendations.map((item) => `<div class="approval-card"><b>${item.summary}</b><div class="approval-meta">${item.recommendationId} · ${item.status} · ${item.severity} · ${item.createdAt || ""}</div><div>${(item.reasonCodes || []).join(", ") || "No reason codes"}</div></div>`).join(""); $("recommendationTimeline").innerHTML = buildRecommendationTimeline(); }
function buildRecommendationTimeline() { if (!state.recommendations.length) return '<div class="timeline-item">No recommendation timeline yet.</div>'; return state.recommendations.map((item) => `<div class="timeline-item ${item.severity === "error" ? "fail" : "warn"}"><b>${item.createdAt || nowTime()} · Recommendation</b>${item.summary}</div><div class="timeline-item"><b>Operator</b>${item.status === "pending" ? "Waiting for approval" : item.status}</div><div class="timeline-item"><b>Result</b>${state.activeProvider || "none"}</div>`).join(""); }
function renderPeers() { const rows = [["hashed3365627006...", "Online", "250MB", "Hash 100%", "ok"], ["hashed5964045005...", "Online", "250MB", "Hash 100%", "ok"], ["hashed3320052003...", "Online", "500MB", "Hash 100%", "ok"]]; const microText = JSON.stringify(state.micro); if (microText.includes("NODE_DISABLED")) rows.push(["candidate-disabled", "Rejected", "0MB", "NODE_DISABLED", "fail"]); if (microText.includes("NODE_OFFLINE")) rows.push(["candidate-offline", "Rejected", "0MB", "NODE_OFFLINE", "fail"]); $("peerList").innerHTML = rows.map((row) => `<div class="peer-row" onclick="openDetailsDrawer('peer-assisted-edge')"><span class="hash">${row[0]}</span><span class="${row[4]}">${row[1]}</span><span>${row[2]}</span><span class="${row[4]}">${row[3]}</span></div>`).join(""); $("trustBoundaryText").textContent = JSON.stringify(state.micro, null, 2); }
function renderPolicyCode() { const policy = { policy: "video-public-peer-assisted-failover", when: state.conditions, then: ["route_to_next_healthy_cdn", "route_to_hash_verified_micro_cdn"], safeguards: { operatorApproval: true, hashVerification: true, livePolicyMutation: false, saveEnabled: false } }; $("policyCode").textContent = state.policyFormat === "json" ? JSON.stringify(policy, null, 2) : `policy: ${policy.policy}\nwhen:\n${state.conditions.map((item) => `  - ${item}`).join("\n")}\nthen:\n  - route_to_next_healthy_cdn\n  - route_to_hash_verified_micro_cdn\nsafeguards:\n  operatorApproval: true\n  hashVerification: true\n  livePolicyMutation: false\n  saveEnabled: false`; }
function renderConditions() { $("conditionList").innerHTML = state.conditions.map((item, index) => `<div class="rule-line"><button>Condition ${index + 1}</button><span>${item}</span></div>`).join(""); renderPolicyCode(); }
function renderReplay() { const attempts = state.routeTrace.attempts || []; const slider = $("replaySlider"); slider.max = String(attempts.length); slider.value = String(Math.min(state.replayIndex, attempts.length)); const partial = replayTrace(state.routeTrace, Number(slider.value)); const step = attempts[Number(slider.value) - 1]; $("replayStep").textContent = step ? `Step ${slider.value}: ${step.provider} -> ${step.result}` : "Step 0: traffic enters Flareless"; $("replayJson").textContent = JSON.stringify(partial, null, 2); }
function renderIncidents() { const attempts = state.routeTrace.attempts || []; const items = attempts.map((a) => `<div class="timeline-item ${isFailed(a.result) ? "fail" : ""}"><b>${nowTime()} · ${a.provider}</b>${a.result}</div>`); if (state.recommendations.length) items.push(`<div class="timeline-item warn"><b>${nowTime()} · Agent</b>Recommendation generated</div>`); items.push(`<div class="timeline-item"><b>${nowTime()} · Result</b>${state.activeProvider || "none"}</div>`); $("incidentTimeline").innerHTML = items.join(""); }
function renderMetrics() { renderSpark("requestSpark", state.metrics.requests); renderSpark("latencySpark", state.metrics.latency); renderSpark("errorSpark", state.metrics.errors); renderDistribution(); }
function renderSpark(id, values) { const max = Math.max(...values, 1); $(id).innerHTML = values.map((value) => `<span style="height:${Math.max(8, (value / max) * 100)}%"></span>`).join(""); }
function renderDistribution() { const providers = state.providers.length ? state.providers : providerIds().map((name) => ({ name })); $("providerDistribution").innerHTML = providers.map((p, i) => { const pct = p.name === state.activeProvider ? 58 : [25, 17, 12, 8, 6][i] || 10; return `<div class="dist-row"><span>${providerDisplayName(p)}</span><div class="dist-bar"><span style="width:${pct}%"></span></div><b>${pct}%</b></div>`; }).join(""); }
function renderEvents() { $("eventsTable").innerHTML = state.events.map((event) => `<tr><td>${event.time}</td><td>${event.type}</td><td><code>${escapeHtml(JSON.stringify(event.payload))}</code></td></tr>`).join(""); }

function topologyState(id) { const attempts = state.routeTrace.attempts || []; const attempt = attempts.find((item) => item.provider === id); const result = attempt?.result || ""; const node = topologyNodes().find((item) => item.id === id) || {}; if (["client-us", "flareless"].includes(id)) return "active"; if (id === state.activeProvider) return "active"; if (isFailed(result)) return "failed"; if (node.kind === "peer") return state.routeTrace.selectedFallback === "peer-fallback" || state.activeProvider === id ? "peer-active" : "peer-standby"; if (node.kind === "origin") return state.activeProvider ? "active" : "standby"; return "standby"; }
function topologyColors(id) { const mode = topologyState(id); const map = { active: { fill: "#12251f", stroke: "#46f0a0", text: "#f1fff7", opacity: 1, glow: "url(#greenGlow)" }, failed: { fill: "#25131a", stroke: "#f04455", text: "#ffe6ea", opacity: 1, glow: "url(#redGlow)" }, standby: { fill: "#101820", stroke: "#43515e", text: "#8e9cab", opacity: 0.48, glow: "none" }, "peer-active": { fill: "#10232c", stroke: "#62c8ff", text: "#e9fbff", opacity: 1, glow: "url(#blueGlow)" }, "peer-standby": { fill: "#0f1a22", stroke: "#315365", text: "#8ca8b6", opacity: 0.55, glow: "none" } }; return map[mode] || map.standby; }
function topologyLinkMode(link) { if (link.from === "client-us" && link.to === "flareless") return "active"; if (link.to === state.activeProvider || link.from === state.activeProvider) return "active"; const failed = (state.routeTrace.attempts || []).some((a) => a.provider === link.to && isFailed(a.result)); if (failed) return "failed"; const toNode = topologyNodes().find((n) => n.id === link.to) || {}; if (toNode.kind === "peer" && state.routeTrace.selectedFallback === "peer-fallback") return "peer-active"; return "standby"; }
function topologyStroke(mode) { if (mode === "active") return "#46f0a0"; if (mode === "failed") return "#f04455"; if (mode === "peer-active") return "#62c8ff"; return "#314454"; }
function topoNode(n) { const c = topologyColors(n.id); const status = topologyState(n.id).replace("peer-", ""); const sub = n.id === state.activeProvider ? "active" : status; const x = n.x ?? 100; const y = n.y ?? 100; const r = n.r ?? 38; return `<g class="topo-node clickable-topology" onclick="openDetailsDrawer('${escapeHtml(n.id)}')" data-id="${escapeHtml(n.id)}" opacity="${c.opacity}"><circle class="topology-node-shadow" cx="${x}" cy="${y}" r="${r + 12}" fill="${c.stroke}" filter="${c.glow}"/><circle cx="${x}" cy="${y}" r="${r}" fill="${c.fill}" stroke="${c.stroke}" stroke-width="3" filter="${c.glow}"/><text x="${x}" y="${y - 2}" text-anchor="middle" fill="${c.text}" font-size="18" font-family="Segoe UI">${escapeHtml(n.label || n.id)}</text><text x="${x}" y="${y + 20}" text-anchor="middle" fill="${c.stroke}" font-size="11" font-family="Consolas">${sub}</text>${status === "failed" ? `<text x="${x + r - 4}" y="${y - r + 12}" text-anchor="middle" fill="#fff" font-size="16" font-family="Segoe UI">×</text>` : ""}</g>`; }
function edgeMetric(link) { const provider = state.providers.find((p) => p.name === link.to || p.name === link.from); if (provider?.latencyMs) return `${provider.latencyMs} ms`; return link.label || "link"; }
function topoLink(link, nodeMap) { const a = nodeMap.get(link.from); const b = nodeMap.get(link.to); if (!a || !b) return ""; const mode = topologyLinkMode(link); const stroke = topologyStroke(mode); const opacity = mode === "standby" ? 0.34 : 0.9; const dash = mode === "failed" ? "8 8" : mode === "standby" ? "4 10" : ""; const packet = mode !== "standby" ? `<circle r="5" fill="${stroke}" opacity="0.95"><animateMotion dur="1.8s" repeatCount="indefinite" path="M${a.x},${a.y} L${b.x},${b.y}"/></circle>` : ""; const midX = ((a.x ?? 0) + (b.x ?? 0)) / 2; const midY = ((a.y ?? 0) + (b.y ?? 0)) / 2 - 8; return `<g class="${mode === "active" || mode === "peer-active" ? "active-path" : ""}"><line id="${escapeHtml(link.id || `${link.from}-${link.to}`)}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${stroke}" stroke-width="4" opacity="${opacity}" stroke-dasharray="${dash}"/>${packet}<text class="topology-edge-label ${mode}" x="${midX}" y="${midY}" text-anchor="middle">${escapeHtml(edgeMetric(link))}</text></g>`; }
function renderTopology() { const tNodes = topologyNodes(); const nodeMap = new Map(tNodes.map((n) => [n.id, n])); const links = topologyLinks(); const attempts = state.routeTrace.attempts || []; const failedCount = attempts.filter((a) => isFailed(a.result)).length; const activeLabel = state.activeProvider ? (nodeMap.get(state.activeProvider)?.label || state.activeProvider) : "none"; const defs = `<defs><filter id="greenGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><filter id="redGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><filter id="blueGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>`; $("topologySvg").innerHTML = `${defs}<rect x="0" y="0" width="900" height="420" fill="#06101a"/><text x="24" y="34" fill="#eaf6ff" font-size="16" font-family="Segoe UI" font-weight="700">Living Topology</text><text x="24" y="56" fill="#91a4b5" font-size="12" font-family="Consolas">active=${escapeHtml(activeLabel)} · failed=${failedCount} · config nodes=${tNodes.length} · click nodes for details</text>${links.map((l) => topoLink(l, nodeMap)).join("")}${tNodes.map(topoNode).join("")}<g transform="translate(24 350)"><rect width="500" height="44" rx="10" fill="#0b1520" stroke="rgba(255,255,255,.08)"/><circle cx="20" cy="22" r="6" fill="#46f0a0"/><text x="34" y="26" fill="#dcecff" font-size="12">active path</text><circle cx="130" cy="22" r="6" fill="#43515e"/><text x="144" y="26" fill="#dcecff" font-size="12">standby</text><circle cx="228" cy="22" r="6" fill="#f04455"/><text x="242" y="26" fill="#dcecff" font-size="12">failed</text><circle cx="310" cy="22" r="6" fill="#62c8ff"/><text x="324" y="26" fill="#dcecff" font-size="12">Micro CDN</text><text x="420" y="26" fill="#91a4b5" font-size="12">editable JSON</text></g>`; }
function renderTopologyEditor() { const el = $("topologyConfigText"); if (!el || document.activeElement === el) return; el.value = JSON.stringify(state.topologyConfig, null, 2); }
function applyTopologyFromText() { try { const next = JSON.parse($("topologyConfigText").value); if (!Array.isArray(next.nodes) || !Array.isArray(next.links)) throw new Error("nodes and links arrays are required"); state.topologyConfig = next; syncNodeRegistry(); renderTopology(); renderScenarioBuilder(); recordEvent("TOPOLOGY_CONFIG_APPLIED", { nodes: next.nodes.length, links: next.links.length }); toast("Topology applied locally."); } catch (error) { toast(`Topology JSON error: ${error.message}`); } }
async function saveTopologyConfig() { applyTopologyFromText(); const saved = await api("/topology/config", state.topologyConfig); state.topologyConfig = saved; syncNodeRegistry(); renderTopologyEditor(); renderTopology(); recordEvent("TOPOLOGY_CONFIG_SAVED", { nodes: saved.nodes.length, links: saved.links.length }); toast("Topology saved to local JSON."); }
async function reloadTopologyConfig() { const cfg = await api("/topology/config"); state.topologyConfig = cfg; syncNodeRegistry(); renderTopologyEditor(); renderTopology(); renderScenarioBuilder(); recordEvent("TOPOLOGY_CONFIG_RELOADED", { nodes: cfg.nodes.length, links: cfg.links.length }); toast("Topology reloaded."); }
function resetTopologyConfig() { state.topologyConfig = structuredClone(defaultTopologyConfig); syncNodeRegistry(); renderTopologyEditor(); renderTopology(); renderScenarioBuilder(); recordEvent("TOPOLOGY_CONFIG_RESET", {}); toast("Default topology restored locally. Save to persist."); }
function renderHistory() { $("historyTable").innerHTML = state.history.map((item) => `<tr><td>${item.time}</td><td>${item.scenario}</td><td>${item.result}</td><td>${item.provider || "none"}</td></tr>`).join(""); }
function renderExplanation(status) { const attempts = state.routeTrace.attempts || []; const failed = attempts.filter((a) => isFailed(a.result)); $("explanationText").textContent = `Why did routing change?\n\n${failed.length ? failed.map((a) => `${a.provider} returned ${a.result}.`).join("\n") : "The primary provider path is healthy."}\n\nSelected provider: ${status.activeProvider || "none"}.\nTopology is driven by editable provider/link config plus route trace state.\nNo live policy mutations occurred.`; }
function formatHeaders(headers) { return Object.entries(headers || {}).map(([key, value]) => `${key}: ${value}`).join("\n") || "No headers loaded."; }
function formatTraffic(status, trace, providers) { return `Scenario: ${status.scenarioId}\nActive: ${status.activeProvider || "none"}\n\n${providers.map((provider) => `${provider.name.padEnd(7)} ${String(provider.status).padEnd(9)} ${provider.lastResult}`).join("\n")}\n\n${(trace.attempts || []).map((attempt) => `${attempt.provider}: ${attempt.result}`).join("\n")}`; }
function formatDiff(status, trace) { const failed = (trace.attempts || []).filter((item) => item.result !== "PROVIDER_SUCCESS").map((item) => item.provider); return `before:\n  activeProvider: primary\n  cooldown: []\n\nafter:\n  routeReason: ${status.routeReason || "unknown"}\n  activeProvider: ${status.activeProvider || "none"}\n  cooldown: ${JSON.stringify(failed)}\n  livePolicyMutation: false`; }

function providerDetails(id) { const node = topologyNodes().find((n) => n.id === id) || { id, label: id, kind: "unknown" }; const provider = state.providers.find((p) => p.name === id) || { name: id, status: topologyState(id), latencyMs: "--", lastResult: topologyState(id) }; const attempts = (state.routeTrace.attempts || []).filter((a) => a.provider === id); const links = topologyLinks().filter((l) => l.from === id || l.to === id); return { title: node.label || id, type: node.kind || "provider", status: topologyState(id), latency: provider.latencyMs || "--", lastResult: provider.lastResult || attempts.at(-1)?.result || "standby", role: id === state.activeProvider ? "active" : "standby", attempts, links }; }
function openDetailsDrawer(id) { const drawer = $("detailsDrawer"); const body = $("detailsDrawerBody"); const d = providerDetails(id); const trust = d.type === "peer" ? `<div class="kv"><span>Trust</span><b>${escapeHtml(state.micro.trustModel || "hash verified local cache")}</b></div><div class="kv"><span>Hash</span><b>${escapeHtml(state.micro.hashVerifiedLocalCache || "implemented")}</b></div>` : ""; body.innerHTML = `<div class="drawer-title">${escapeHtml(d.title)}</div><div class="drawer-sub">${escapeHtml(id)} · ${escapeHtml(d.type)}</div><div class="kv"><span>Status</span><b>${escapeHtml(d.status)}</b></div><div class="kv"><span>Role</span><b>${escapeHtml(d.role)}</b></div><div class="kv"><span>Latency</span><b>${escapeHtml(d.latency)} ms</b></div><div class="kv"><span>Last Result</span><b>${escapeHtml(d.lastResult)}</b></div><div class="kv"><span>Links</span><b>${d.links.map((l) => escapeHtml(`${l.from} → ${l.to}`)).join("<br>") || "none"}</b></div>${trust}<div class="drawer-title">Route Attempts</div><pre>${escapeHtml(JSON.stringify(d.attempts, null, 2))}</pre>`; drawer.classList.add("open"); }
function closeDetailsDrawer() { $("detailsDrawer").classList.remove("open"); }
function scenarioObject() { return { id: `custom-${Date.now()}`, name: "UI custom failover chain", routeKey: "route:/custom", policyId: "ui-custom-policy", attempts: state.scenarioSteps, agent: { severity: "warning", summary: "Custom failover chain generated in UI.", reasonCodes: ["CUSTOM_CHAIN"], action: "REVIEW" } }; }
function renderScenarioBuilder() { const providers = providerIds(); $("scenarioSteps").innerHTML = state.scenarioSteps.map((step, index) => `<div class="scenario-step"><select data-step-provider="${index}">${providers.map((p) => `<option ${p === step.provider ? "selected" : ""}>${p}</option>`).join("")}</select><select data-step-result="${index}">${resultOptions.map((r) => `<option ${r === step.result ? "selected" : ""}>${r}</option>`).join("")}</select></div>`).join(""); const obj = scenarioObject(); $("scenarioExport").textContent = state.scenarioFormat === "json" ? JSON.stringify(obj, null, 2) : `id: ${obj.id}\nname: ${obj.name}\nattempts:\n${obj.attempts.map((s) => `  - provider: ${s.provider}\n    result: ${s.result}`).join("\n")}`; document.querySelectorAll("[data-step-provider]").forEach((el) => el.onchange = () => { state.scenarioSteps[Number(el.dataset.stepProvider)].provider = el.value; renderScenarioBuilder(); }); document.querySelectorAll("[data-step-result]").forEach((el) => el.onchange = () => { state.scenarioSteps[Number(el.dataset.stepResult)].result = el.value; renderScenarioBuilder(); }); }
async function runCustomScenario() { await api("/route/custom-scenario", { scenario: scenarioObject() }); await refresh(); state.history.unshift({ time: nowTime(), scenario: "custom-ui", result: state.routeTrace.finalStatus?.reason || "unknown", provider: state.activeProvider }); saveLocalState(false); toast("Custom scenario applied."); }
async function saveLocalState(showToast = true) { await api("/state/local-ui", { history: state.history, events: state.events, scenarioSteps: state.scenarioSteps }); if (showToast) toast("Local UI state saved."); }
async function loadInitialState() { try { const [saved, topo] = await Promise.all([api("/state/local-ui"), api("/topology/config")]); state.history = saved.history || []; state.events = saved.events || []; if (Array.isArray(saved.scenarioSteps) && saved.scenarioSteps.length) state.scenarioSteps = saved.scenarioSteps; state.topologyConfig = topo; syncNodeRegistry(); renderTopologyEditor(); renderScenarioBuilder(); renderHistory(); renderEvents(); renderTopology(); } catch (error) { recordEvent("LOCAL_STATE_LOAD_FAILED", { message: error.message }); } }
async function decideLatest(action) { const item = [...state.recommendations].reverse().find((rec) => rec.status === "pending"); if (!item) return toast("No pending recommendation."); await api(`/agent/recommendations/${item.recommendationId}/${action}`, { operator: "local-operator", note: `${action} from UI` }); recordEvent(action === "approve" ? "RECOMMENDATION_APPROVED" : "RECOMMENDATION_REJECTED", { recommendationId: item.recommendationId }); await refresh(); saveLocalState(false); toast(`Recommendation ${action}d.`); }
async function runScenario() { await api("/route/simulate", { scenarioId: $("scenarioSelect").value }); await refresh(); state.history.unshift({ time: nowTime(), scenario: state.scenarioId, result: state.routeTrace.finalStatus?.reason || "unknown", provider: state.activeProvider }); state.history = state.history.slice(0, 60); recordEvent("SCENARIO_RUN", { scenarioId: state.scenarioId }); renderHistory(); saveLocalState(false); toast("Scenario applied."); }
async function applyOutage() { $("scenarioSelect").value = "http-status-failover"; await runScenario(); }
function startPolling() { if (state.timer) return; state.timer = setInterval(refresh, 1000); $("pollBtn").disabled = true; $("pauseBtn").disabled = false; recordEvent("POLLING_STARTED", {}); refresh(); }
function pausePolling() { if (state.timer) clearInterval(state.timer); state.timer = null; $("pollBtn").disabled = false; $("pauseBtn").disabled = true; recordEvent("POLLING_PAUSED", {}); updateHeader({ routeReason: $("routeReason").textContent }); renderEvents(); }
function showView(viewId) { state.currentPage = viewId; document.querySelectorAll(".nav-item").forEach((button) => button.classList.toggle("active", button.dataset.view === viewId)); document.querySelectorAll(".view").forEach((view) => view.classList.toggle("active", view.id === viewId)); recordEvent("PAGE_CHANGED", { viewId }); renderEvents(); if (viewId === "dashboard") setTimeout(() => state.map?.resize(), 50); if (viewId === "topology") setTimeout(() => { renderTopology(); renderTopologyEditor(); }, 50); }
function updateReplayFromSlider() { state.replayIndex = Number($("replaySlider").value); const partial = replayTrace(state.routeTrace, state.replayIndex); if (state.mapReady) state.map.getSource("flareless-live")?.setData(buildMapGeoJson(partial, state.providers)); renderReplay(); recordEvent("REPLAY_STEP_CHANGED", { replayIndex: state.replayIndex }); }
function bindEvents() { $("runScenarioBtn").addEventListener("click", runScenario); $("refreshBtn").addEventListener("click", refresh); $("pollBtn").addEventListener("click", startPolling); $("pauseBtn").addEventListener("click", pausePolling); $("applyOutageBtn").addEventListener("click", applyOutage); $("addConditionBtn").addEventListener("click", () => { state.conditions.push("New condition == true"); renderConditions(); toast("Condition added."); }); $("removeConditionBtn").addEventListener("click", () => { if (state.conditions.length > 1) state.conditions.pop(); renderConditions(); toast("Condition removed."); }); $("yamlBtn").addEventListener("click", () => { state.policyFormat = "yaml"; $("yamlBtn").classList.add("active"); $("jsonBtn").classList.remove("active"); renderPolicyCode(); }); $("jsonBtn").addEventListener("click", () => { state.policyFormat = "json"; $("jsonBtn").classList.add("active"); $("yamlBtn").classList.remove("active"); renderPolicyCode(); }); $("testPolicyBtn").addEventListener("click", () => toast("Policy test passed in local simulation. Save remains disabled.")); $("approveBtn").addEventListener("click", () => decideLatest("approve")); $("rejectBtn").addEventListener("click", () => decideLatest("reject")); $("replaySlider").addEventListener("input", updateReplayFromSlider); $("addStepBtn").addEventListener("click", () => { state.scenarioSteps.push({ provider: providerIds()[0] || "cdn-a", result: "TIMEOUT" }); renderScenarioBuilder(); }); $("removeStepBtn").addEventListener("click", () => { if (state.scenarioSteps.length > 1) state.scenarioSteps.pop(); renderScenarioBuilder(); }); $("runCustomScenarioBtn").addEventListener("click", runCustomScenario); $("scenarioJsonBtn").addEventListener("click", () => { state.scenarioFormat = "json"; $("scenarioJsonBtn").classList.add("active"); $("scenarioYamlBtn").classList.remove("active"); renderScenarioBuilder(); }); $("scenarioYamlBtn").addEventListener("click", () => { state.scenarioFormat = "yaml"; $("scenarioYamlBtn").classList.add("active"); $("scenarioJsonBtn").classList.remove("active"); renderScenarioBuilder(); }); $("saveLocalStateBtn").addEventListener("click", () => saveLocalState(true)); $("closeDrawerBtn").addEventListener("click", closeDetailsDrawer); $("applyTopologyBtn").addEventListener("click", applyTopologyFromText); $("saveTopologyBtn").addEventListener("click", saveTopologyConfig); $("reloadTopologyBtn").addEventListener("click", reloadTopologyConfig); $("resetTopologyBtn").addEventListener("click", resetTopologyConfig); document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => showView(button.dataset.view))); }

injectOperationalStyles(); bindEvents(); syncNodeRegistry(); renderConditions(); renderMetrics(); renderEvents(); renderTopology(); renderTopologyEditor(); renderScenarioBuilder(); initMap(); loadInitialState(); recordEvent("UI_READY", { paused: true, topology: "living" });
